apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sparrow.fullname" . }}
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
data:
  .sparrow.yaml: |
	{{- .Values.config | toYaml | nindent 4 }}
