{{- if .Values.sparrow}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sparrow.fullname" . }}
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
data:
  apiAddress: {{ .Values.sparrow.apiAddress | default ":8080" | b64enc | quote }}
  loaderFilePath: {{ .Values.sparrow.loaderFilePath | default "config.yaml" | b64enc | quote }}
  loaderHttpRetryCount: {{ .Values.sparrow.loaderHttpRetryCount | default "3" | b64enc | quote }}
  loaderHttpRetryDelay: {{ .Values.sparrow.loaderHttpRetryDelay | default "1" | b64enc | quote }}
  loaderHttpTimeout: {{ .Values.sparrow.loaderHttpTimeout | default "30" | b64enc | quote }}
  {{- if .Values.sparrow.loaderHttpToken}}
  loaderHttpToken: {{ .Values.sparrow.loaderHttpToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.sparrow.loaderHttpUrl}}
  loaderHttpUrl: {{ .Values.sparrow.loaderHttpUrl | b64enc | quote }}
  {{- end }}
  loaderInterval: {{ .Values.sparrow.loaderInterval | default "300" |b64enc | quote }}
  loaderType: {{ .Values.sparrow.loaderType | default "http" |b64enc | quote }}
{{- end }}
