apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sparrow.fullname" . }}
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
data:
  .sparrow.yaml: {{ toYaml .Values.config | b64enc }}
