// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package metrics

import (
	"context"
	"github.com/prometheus/client_golang/prometheus"
	"sync"
)

// Ensure, that MetricsMock does implement Metrics.
// If this is not the case, regenerate this file with moq.
var _ Metrics = &MetricsMock{}

// MetricsMock is a mock implementation of Metrics.
//
//	func TestSomethingThatUsesMetrics(t *testing.T) {
//
//		// make and configure a mocked Metrics
//		mockedMetrics := &MetricsMock{
//			GetRegistryFunc: func() *prometheus.Registry {
//				panic("mock out the GetRegistry method")
//			},
//			InitTracingFunc: func(ctx context.Context) error {
//				panic("mock out the InitTracing method")
//			},
//			ShutdownFunc: func(ctx context.Context) error {
//				panic("mock out the Shutdown method")
//			},
//		}
//
//		// use mockedMetrics in code that requires Metrics
//		// and then make assertions.
//
//	}
type MetricsMock struct {
	// GetRegistryFunc mocks the GetRegistry method.
	GetRegistryFunc func() *prometheus.Registry

	// InitTracingFunc mocks the InitTracing method.
	InitTracingFunc func(ctx context.Context) error

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// GetRegistry holds details about calls to the GetRegistry method.
		GetRegistry []struct {
		}
		// InitTracing holds details about calls to the InitTracing method.
		InitTracing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetRegistry sync.RWMutex
	lockInitTracing sync.RWMutex
	lockShutdown    sync.RWMutex
}

// GetRegistry calls GetRegistryFunc.
func (mock *MetricsMock) GetRegistry() *prometheus.Registry {
	if mock.GetRegistryFunc == nil {
		panic("MetricsMock.GetRegistryFunc: method is nil but Metrics.GetRegistry was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetRegistry.Lock()
	mock.calls.GetRegistry = append(mock.calls.GetRegistry, callInfo)
	mock.lockGetRegistry.Unlock()
	return mock.GetRegistryFunc()
}

// GetRegistryCalls gets all the calls that were made to GetRegistry.
// Check the length with:
//
//	len(mockedMetrics.GetRegistryCalls())
func (mock *MetricsMock) GetRegistryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetRegistry.RLock()
	calls = mock.calls.GetRegistry
	mock.lockGetRegistry.RUnlock()
	return calls
}

// InitTracing calls InitTracingFunc.
func (mock *MetricsMock) InitTracing(ctx context.Context) error {
	if mock.InitTracingFunc == nil {
		panic("MetricsMock.InitTracingFunc: method is nil but Metrics.InitTracing was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockInitTracing.Lock()
	mock.calls.InitTracing = append(mock.calls.InitTracing, callInfo)
	mock.lockInitTracing.Unlock()
	return mock.InitTracingFunc(ctx)
}

// InitTracingCalls gets all the calls that were made to InitTracing.
// Check the length with:
//
//	len(mockedMetrics.InitTracingCalls())
func (mock *MetricsMock) InitTracingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockInitTracing.RLock()
	calls = mock.calls.InitTracing
	mock.lockInitTracing.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *MetricsMock) Shutdown(ctx context.Context) error {
	if mock.ShutdownFunc == nil {
		panic("MetricsMock.ShutdownFunc: method is nil but Metrics.Shutdown was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc(ctx)
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//
//	len(mockedMetrics.ShutdownCalls())
func (mock *MetricsMock) ShutdownCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}
