name: Feature request
description: Suggest an idea for this project
title: "Feature: "
labels: ["enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if an issue already exists for your feature request.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution Description
      description: Describe the solution you'd like.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Who can address the issue?
      description: Is any special expertise required to resolve this issue?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
