name: Prune GHCR

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  prune_images:
    name: Prune old sparrow images
    runs-on: ubuntu-latest

    steps:
      - name: Prune Images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: sparrow
          keep-younger-than: 7 # days
          prune-untagged: true
          prune-tags-regexes: |
            commit-.*$

      - name: Prune Charts
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: charts/sparrow
          keep-younger-than: 7 # days
          prune-untagged: true
          prune-tags-regexes: |
            commit-.*$
