name: Prune GHCR

on:
  push:
  pull_request:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  prune_images:
    name: Prune old sparrow images
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
    
      - name: Prune Images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: caas-team
          container: sparrow # Package name
          dry-run: true # Dry-run first, then change to `false`
          keep-younger-than: 7 # days
          keep-last: 2
          prune-untagged: true
          keep-tags: |
            latest
          keep-tags-regexes: |
            ^v
          prune-tags-regexes: |
            ^commit-

      - name: Prune Charts
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: caas-team
          container: charts/sparrow # Package name
          dry-run: true # Dry-run first, then change to `false`
          keep-younger-than: 7 # days
          keep-last: 2
          prune-untagged: true
          prune-tags-regexes: |
            '(?<=:\s*).*\bcommit\b.*'